version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/deploy/api_back
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu/deploy/api_back
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  BeforeInstall:
    - location: scripts/fix-permissions.sh
      timeout: 300
      runas: root
    - location: scripts/download_env.sh
      timeout: 2000
      runas: ubuntu
  
  AfterInstall:
    - location: scripts/blue-green-deploy.sh
      timeout: 2000
      runas: root
