services:
  # FastAPI - Blue (포트 8000)
  fastapi-blue:
    build:
      context: .
    container_name: fastapi-blue
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PORT=8000
    env_file:
      - .env
    networks:
      - app-network

  # FastAPI - Green (포트 8001)
  fastapi-green:
    build:
      context: .
    container_name: fastapi-green
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    environment:
      - PORT=8000
    env_file:
      - .env
    networks:
      - app-network

  # Nginx 로드 밸런서
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    external: true
    name: fastapi-shared-network
